"""Public domain contract for Point Audit."""

from point_audit.domain.enums import (
    DatePrecision,
    DeltaSign,
    EventCategory,
    EventType,
    ParseSource,
    ReviewAction,
    ReviewStatus,
    RuleMatchStatus,
    SourceColumn,
    TimelineItemType,
    WarningCode,
)
from point_audit.domain.models import (
    CalculatedRowTotals,
    DatePeriodValidation,
    DeclaredRowTotals,
    DomainWarning,
    DuplicateMatch,
    EventCandidate,
    ParsedEvent,
    PersonReconciliation,
    PersonSummary,
    RawCell,
    RawWorkbookRow,
    ReviewRecord,
    RuleConflict,
    RuleDefinition,
    RuleMatch,
    ScoringPeriod,
    TimelineItem,
    ValidationResult,
)
from point_audit.domain.types import (
    ConfidenceDecimal,
    FiniteDecimal,
    NonNegativeDecimal,
    TextSpan,
    build_event_id,
)

DOMAIN_CONTRACT_VERSION = "0.4.0"

__all__ = [
    "CalculatedRowTotals",
    "ConfidenceDecimal",
    "DatePeriodValidation",
    "DatePrecision",
    "DeclaredRowTotals",
    "DeltaSign",
    "DOMAIN_CONTRACT_VERSION",
    "DomainWarning",
    "DuplicateMatch",
    "EventCandidate",
    "EventCategory",
    "EventType",
    "FiniteDecimal",
    "NonNegativeDecimal",
    "ParseSource",
    "ParsedEvent",
    "PersonReconciliation",
    "PersonSummary",
    "RawCell",
    "RawWorkbookRow",
    "ReviewAction",
    "ReviewRecord",
    "ReviewStatus",
    "RuleConflict",
    "RuleDefinition",
    "RuleMatch",
    "RuleMatchStatus",
    "ScoringPeriod",
    "SourceColumn",
    "TextSpan",
    "TimelineItem",
    "TimelineItemType",
    "ValidationResult",
    "WarningCode",
    "build_event_id",
]
